---
- 
  class: Delicious
  name: delicious
  url: http://feeds.delicious.com/rss/matthias_georgi
-
  class: FlickrAggregation
  name: flickr  
  url: http://api.flickr.com/services/feeds/photos_public.gne?id=31771251@N05&lang=en-us&format=rss_200
- 
  class: Fortythree
  name: fortythree
  url: http://www.43things.com/rss/uber/author?username=matthiasgeorgi
