delicious_feed: http://feeds.delicious.com/rss/matthias_georgi
flickr_feed: http://api.flickr.com/services/feeds/photos_public.gne?id=31771251@N05&lang=en-us&format=rss_200
fortythree_feed: http://www.43things.com/rss/uber/author?username=matthiasgeorgi
