---
javascripts_path: javascripts
stylesheets_path: stylesheets
images_path: images
javascript_files:
  - jquery.min
  - jquery-form
  - swfobject
  - shockwaves
  - comments
  - highlight
  - languages/xml
  - languages/html
  - languages/javascript
  - languages/ruby
  - languages/lisp
stylesheet_files:
  - reset
  - grid
  - typography
  - highlight
  - style
