--- 
stylesheets_path: stylesheets
images_path: images
stylesheet_files: 
- reset
- typo
- table
- list
- grid
- header
- sidebar
- article
- comments
- coderay
javascript_files: 
- jquery.min
- jquery-form.min
- swfobject
- shockwaves
- comments
- coderay
javascripts_path: javascripts
