---
javascripts_path: javascripts
stylesheets_path: stylesheets
images_path: images
javascript_files:
  - jquery.min
  - jquery-form.min
  - swfobject
  - shockwaves
  - comments
stylesheet_files:
  - reset
  - typo
  - table
  - form
  - list
  - grid
  - header
  - sidebar
  - article
  - comments
  - coderay
