--- 
author: Matthias Georgi
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
description: Webdev, Gamedev, Interaction Design
language: en
title: Matthias Georgi
url: http://www.matthias-georgi.de
