--- 
author: Matthias Georgi
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
description: a crystalline mind in a cloud of code
language: en
title: Matthias Georgi
url: http://www.matthias-georgi.de
