--- 
repository: root@213.239.215.244:/var/www/matthias-georgi.de/
author: Matthias Georgi
title: Matthias Georgi
url: http://www.matthias-georgi.de
language: en
description: Webdev, Gamedev, Interaction Design
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
