--- 
repository: root@213.239.215.244:/var/www/matthias-georgi.de/
title: Matthias Georgi
author: Matthias Georgi
language: en
url: http://www.matthias-georgi.de
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
description: Webdev, Gamedev, Interaction Design
