--- 
title: Matthias Georgi
language: en
author: Matthias Georgi
url: http://www.matthias-georgi.de
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
description: Webdev, Gamedev, Interaction Design
