--- 
language: en
title: Matthias Georgi
url: http://www.matthias-georgi.de
author: Matthias Georgi
description: Webdev, Gamedev, Interaction Design
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
