--- 
title: Matthias Georgi
author: Matthias Georgi
url: http://www.matthias-georgi.de
language: en
description: Webdev, Gamedev, Interaction Design
categories: 
- Ruby
- Javascript
- Actionscript
- Emacs
